### ISSUE TITLE
Drop Kinetic support?

### ISSUE THREAD

**Issue by gpdas** [LCAS/CMP9767M#53]
@marc-hanheide Can we drop Kinetic support in this and merge `melodic-devel` to `master`?

**Comment by marc-hanheide** [comment]
That depends on the installation of our lab computers. I suspect it will be melodic, so, yes, but first branch the current `master` into a new `kinetic-devel`

**Comment by gpdas** [comment]
OK. I've created a new branch `kinetic-devel` from `master`. 

Also created a PR #55 to merge `melodic-devel` to `master`. But will wait for #51 (to address the Thorvald `tf_prefix` updates) to be merged before that. Only melodic Thorvald binaries seem to have those `tf_prefix` changes at the moment. 
I created another PR to master for the same changes in master, but only then I realised that kinetic Thorvald binaries are really old. So closed that. I will check with Jaime what is its status and make a PR to kinetic-devel once that is sorted.

**Comment by marc-hanheide** [comment]
So, I have now merged #55 , subsequently deleted the `melodic-devel` branch, and configured the CI server to now test `master` against `melodic` and `kinetic-devel` against `kinetic`. We shall retain `kinetic-devel` and ideally keep up to date and working, but the main branch is now `master` (for `melodic`).

**Comment by marc-hanheide** [comment]
To inform: it has now been released into melodic also as released packages and is available for people to try out (good starting point to play with a thorvald simulation)
